worker_processes 10;
error_log stderr info;
pid /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events{
  worker_connections 4096;
}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    log_format main escape=json '{"timestamp": "$time_local", "service": "nginx", "type":"std", "address": "$remote_addr", "host": "$http_host", "request": $request, "resp_body_size": $body_bytes_sent, "status": $status, "user_agent": "$http_user_agent"}';

    access_log /dev/stdout main;

    sendfile            on;
    keepalive_timeout   65;

    include /etc/nginx/mime.types;
    default_type        application/octet-stream;
    #limit request body size to 100k
    client_max_body_size 100k;

    server {
        listen 8080;
        server_name ${CSP_HOSTNAME};
        server_tokens off;
        absolute_redirect off;
        port_in_redirect off;

        ### avoid click-jacking
        add_header X-Frame-Options SAMEORIGIN;
        ### Enable the Cross-site scripting (XSS) filter
        add_header X-XSS-Protection "1; mode=block";

        set $csp_nonce_value $request_id;

        # https://content-security-policy.com/examples/allow-inline-script/
        # keep unsafe-inline instead of nonce for script and styles loading purposes
        add_header Content-Security-Policy "base-uri 'self'; connect-src 'self'; frame-ancestors 'self'; frame-src 'self'; img-src 'self' data:; media-src 'self'; object-src 'none'; script-src 'self' ; style-src 'self' 'unsafe-inline'";
        add_header X-Content-Type-Options nosniff;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header Cross-Origin-Opener-Policy "same-origin";
        add_header Cache-Control "max-age=600";
        add_header Referrer-Policy "strict-origin-when-cross-origin";
        add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
        ssl_session_tickets off;

        root /usr/share/nginx/html;
        index index.html;
        
        # Set a default 404 page for the root location
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }

        location ~* \.(?:js|css|svg|png|jpg|jpeg|gif|woff2?)$ {
            expires 7d;
            add_header Cache-Control "public";
            try_files $uri =404;
        }

        location ~ /\. {
            deny all;
            return 404;
        }

        # Set a default 404 page for the /kommentierung/ location
        location = /kommentierung/404.html {
            internal;
        }

        location /kommentierung/ {
            error_page 404 /kommentierung/404.html;
            autoindex off;
            try_files $uri $uri/ =404;
            sub_filter '__ngCspNonce__'  "${csp_nonce_value}";
            sub_filter_once off;
        }

        location / {
            autoindex off;
            try_files $uri $uri/ =404;
            sub_filter '__ngCspNonce__'  "${csp_nonce_value}";
            sub_filter_once off;
        }
    }
}
